### ISSUE TITLE
Add support for other console methods

### ISSUE THREAD

**Issue by khalby786** [KMJ-007/purgeConsole-VsCodeExtension#3]
Currently, only `console.log` statements work. It would be nice to provide support for methods like `console.table`, `console.time`, `console.timeLog` and `console.timeEnd`.

**Comment by KMJ-007** [comment]
Good idea!

**Comment by KMJ-007** [comment]
Thankyou for your patience, here it is, it now supports other console methods also:

https://marketplace.visualstudio.com/items?itemName=KaranJanthe.purgeConsole

ps: I was busy with react-native and regex bug, there for it got delay little :)

**Comment by khalby786** [comment]
No worries, thanks a lot Karan!
